import Head from "next/head";
import styles from "../styles/AboutMe.module.css";

export default function AboutMe() {
  return (
    <div>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className={styles.title}>
          {"About "}
          <span>Me</span>
        </div>
      </div>
    </div>
  );
}
