import Head from "next/head";

export default function Resume() {
  return (
    <div>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>hello4</h1>
      </div>
    </div>
  );
}
