import Head from "next/head";

export default function Work() {
  return (
    <div>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>hello3</h1>
      </div>
    </div>
  );
}
